apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  ruleSelector:
    matchLabels:
      role: prometheus
      prometheus: kube-prometheus
  securityContext:
    fsGroup: 2000
  serviceMonitorNamespaceSelector:
    matchNames:
    - core
  versions:
    prometheus: v2.14.0
    alertmanager: v0.15.3
    nodeExporter: v0.18.1
    kubeStateMetrics: v1.8.0
    grafana: v6.0.2
  podMonitorNamespaceSelector:
    matchNames:
      - kube-system
      - core
